<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130116001412 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_features_domain_model_feature (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, created DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_features_domain_model_toggle (persistence_object_identifier VARCHAR(40) NOT NULL, feature VARCHAR(40) DEFAULT NULL, account VARCHAR(40) DEFAULT NULL, created DATETIME NOT NULL, start DATETIME NOT NULL, stop DATETIME NOT NULL, role VARCHAR(255) NOT NULL, global TINYINT(1) NOT NULL, INDEX IDX_755584CB1FD77566 (feature), INDEX IDX_755584CB7D3656A4 (account), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_features_domain_model_toggle ADD CONSTRAINT FK_755584CB1FD77566 FOREIGN KEY (feature) REFERENCES famelo_features_domain_model_feature (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_features_domain_model_toggle ADD CONSTRAINT FK_755584CB7D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_features_domain_model_toggle DROP FOREIGN KEY FK_755584CB1FD77566");
		$this->addSql("DROP TABLE famelo_features_domain_model_feature");
		$this->addSql("DROP TABLE famelo_features_domain_model_toggle");
	}
}

?>