<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130121161507 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_features_domain_model_toggle DROP FOREIGN KEY FK_755584CB1FD77566");
		$this->addSql("DROP INDEX IDX_755584CB1FD77566 ON famelo_features_domain_model_toggle");
		$this->addSql("ALTER TABLE famelo_features_domain_model_toggle DROP feature");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_features_domain_model_toggle ADD feature VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_features_domain_model_toggle ADD CONSTRAINT FK_755584CB1FD77566 FOREIGN KEY (feature) REFERENCES famelo_features_domain_model_feature (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_755584CB1FD77566 ON famelo_features_domain_model_toggle (feature)");
	}
}

?>