<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130121162709 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_features_domain_model_feature_toggles_join (features_feature VARCHAR(40) NOT NULL, features_toggle VARCHAR(40) NOT NULL, INDEX IDX_476500B876B74A93 (features_feature), INDEX IDX_476500B84317A618 (features_toggle), PRIMARY KEY(features_feature, features_toggle))");
		$this->addSql("ALTER TABLE famelo_features_domain_model_feature_toggles_join ADD CONSTRAINT FK_476500B876B74A93 FOREIGN KEY (features_feature) REFERENCES famelo_features_domain_model_feature (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_features_domain_model_feature_toggles_join ADD CONSTRAINT FK_476500B84317A618 FOREIGN KEY (features_toggle) REFERENCES famelo_features_domain_model_toggle (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE famelo_features_domain_model_feature_toggles_join");
	}
}

?>